### PR TITLE
Updating for the new options with version 4.2.0

### PR DESCRIPTION
**Pull request by haate**
Files added: 
        images/cardiaDock.png
        images/gaiaMountain.png
        images/lefeinRiver.png
Files actually modified (rather than CRLF changes):
        modified:   ff1_rando_jat.zip
        modified:   items/flags.json
        modified:   items/hosted_items.json
        modified:   items/items.json
        modified:   layouts/shared.json
        modified:   layouts/standard_broadcast.json
        modified:   layouts/tracker.json
        modified:   locations/incentives.json
        modified:   locations/locations.json
        modified:   manifest.json
        modified:   repository.json

### CODE REVIEW

**Comment by haate** [comment]
Visual of modifications to the UI: 
image

**Review by jtoyoda — CHANGES_REQUESTED** [review]
Can you make sure the zip file doesn't contain the old zip file. When I took a look I noticed it had it

**Comment by haate** [comment]
...craaaaaaaap. included that by accident. Extra recursive zip has been removed.

**Review by openhouse-jtoyoda — APPROVED** [review]
Looks good and thanks! Once I'm back from camping and have internet again I'll get dark Moon to replace the icons

**Comment by jtoyoda** [comment]
@haate just an update. Darkmoon is working on new icons which I will send over to you to update this PR with

**Comment by haate** [comment]
No worries. I realized that i didn't get the Cardia Island incentive built in yet. I figure I'll just use the bahamut icon for that one though.

**Comment by haate** [comment]
Here's what the tracker looks like with northern docks, cardia docks, lefein river, gaia mountain, and cardia incentive on. 
image
And here's what we have with the first four off (as those are the only pertinent ones having a different off image)
image

Whilst DM did provide new images for No open, early open, extended open, I felt that those were a bit less clear, and left that image as the letters.

**Review by jtoyoda — APPROVED** [review]

**Comment by haate** [comment]
hold off on merging, have one more change that will have to be made. Forgot Gaia shortcut is on the Lefein side of the mountains, not the Mirage side.

**Comment by haate** [comment]
alright, NOW it's ready for merging. Got the right chest tagged for cardia incentive, have all the logic corrected, and the images are all (well, almost) the pretty ones provided. Only one that wasn't prettied up was the open/extended open flag.

**Pull request merged**
